name: Makefile CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d

      - name: Test
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run test
  
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build and push image
      run: make docker-push
